name: Java CI with Gradle

# main ë¸Œëœì¹˜ì— push í˜¹ì€ pull request ê°€ merged ì‹œ ë™ì‘.
on:
  push:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      # (1) í”„ë¡œê·¸ë¨ ë¹Œë“œ (Java ë¹Œë“œ) 1) Java ë° Docker ë¹Œë“œë¥¼ ìœ„í•œ í™˜ê²½ ì„¤ì •
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # (1) í”„ë¡œê·¸ë¨ ë¹Œë“œ (Java ë¹Œë“œ) 2) Java ë¹Œë“œë¥¼ ìœ„í•œ ./gradlew íŒŒì¼ ê¶Œí•œ ë³€ê²½
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

 # (1) í”„ë¡œê·¸ë¨ ë¹Œë“œ (Java ë¹Œë“œ) 3) Java ë¹Œë“œ
      - name: Spring Boot Build
        run: ./gradlew clean build

      # ğŸ” Secret ê°’ í™•ì¸ìš© ë””ë²„ê¹… ë‹¨ê³„
      - name: Check DockerHub Username
        run: | 
         echo "DOCKERHUB_USERNAME is: ${{ secrets.DOCKERHUB_USERNAME }}"

      # (2) Docker ì´ë¯¸ì§€ ë¹Œë“œ 1) DockerFile ì„ ê¸°ë°˜ìœ¼ë¡œ Docker Image ë¹Œë“œ
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .
        env:
          DOCKER_BUILDKIT: 0

      # (2) Docker ì´ë¯¸ì§€ ë¹Œë“œ 2) Docker Hub ì— Login
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      # (2) Docker ì´ë¯¸ì§€ ë¹Œë“œ 3) Docker Hub ì— ë¹Œë“œëœ ì´ë¯¸ì§€ push
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo
        
      # (3) CD : Docker ì»¨í…Œì´ë„ˆ ìˆ˜í–‰ 1) Get GitHub IP
      - name: get GitHub IP
        id: ip
        uses: haythem/public-ip@v1.2

      # (3) CD : Docker ì»¨í…Œì´ë„ˆ ìˆ˜í–‰ 2) Configure AWS Credentials - AWS ì ‘ê·¼ ê¶Œí•œ ì·¨ë“(IAM)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # (3) CD : Docker ì»¨í…Œì´ë„ˆ ìˆ˜í–‰ 3) Add github ip to AWS
      - name: Add GitHub IP to AWS
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      # (3) CD : Docker ì»¨í…Œì´ë„ˆ ìˆ˜í–‰ 4) AWS EC2 Server Connect & Docker ëª…ë ¹ì–´ ì‹¤í–‰
      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker stop github-actions-demo
            sudo docker rm github-actions-demo
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo
            sudo docker run -it -d -p 8080:8080 --name github-actions-demo ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo

      # (3) CD : Docker ì»¨í…Œì´ë„ˆ ìˆ˜í–‰ 5) Remove Github IP from security group
      - name: Remove IP FROM security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
